import os
from datetime import datetime

def generate_sop(analysis_report, output_file="SOP.md"):
    """
    Converts an AI analysis report into a structured SOP (Standard Operating Procedure) document.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    sop_content = f"""# AIOps Incident Resolution SOP
**Generated on:** {timestamp}

## 1. Incident Summary
{analysis_report}

## 2. Root Cause Analysis (RCA)
The AI agent analyzed the Docker container state and logs. The identified root cause is detailed in the summary above.

## 3. Resolution Steps
Based on the analysis, please follow these steps to resolve the issue:

- [ ] **Step 1:** Validate the current container state using `docker ps`.
- [ ] **Step 2:** Review the logs for the specific error patterns identified.
- [ ] **Step 3:** Apply the suggested fix provided in the analysis report.
- [ ] **Step 4:** Restart the container and verify health status.

## 4. Prevention & Recommendations
- Implement health checks in the Docker Compose/K8s manifest.
- Set resource limits (CPU/Memory) to prevent OOM (Out-of-Memory) kills.
- Set up proactive monitoring/alerting for the detected error patterns.

---
*Generated by AIOps CLI Agent (gemma4:31b-cloud)*
"""

    try:
        with open(output_file, "w") as f:
            f.write(sop_content)
        return f"SOP successfully generated at {output_file}"
    except Exception as e:
        return f"Error generating SOP: {str(e)}"

if __name__ == "__main__":
    # Test the SOP generator
    test_report = "Container 'web_app' is crashing due to Memory Limit Exceeded. Root cause: memory leak in python app. Fix: Increase memory limit to 1GB."
    print(generate_sop(test_report))
